# Runs the unit tests for the pyroma package
# Based on https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test package

on: [pull_request, push]

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: Tests

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.13', 'pypy-3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install package
        run: pip install -e .[test]
      - name: Run tests
        run: python -bb -X dev -W ignore::UserWarning:setuptools.dist -m unittest -v pyroma.tests
